### ISSUE TITLE
dataset download URL not found

### ISSUE THREAD

**Issue by omerarshad** [Clyde013/Paraphrase-OPT#1]
Hello, unable to download datasets from mentioned urls. Also can you help me to load my own CSV dataset?

**Comment by Clydingus** [comment]
No problem, happy to help. Which of the datasets are you having issues with downloading? 

The Parabank dataset (http://cs.jhu.edu/~vandurme/data/parabank-2.0.zip) does not require any download. This is because the dataset is able to be streamed directly from where it is hosted.

The ParaNMT5m dataset (https://drive.google.com/file/d/19NQ87gEFYu3zOIp_VNYQZgmnwRuSIyJd/view) requires a download from the google drive first. When I initially attempted streaming the dataset directly from google drive to skip any large download process, there is an issue with streaming large datasets hosted on google drive, so the only recourse is to download the dataset in full.

If you want to load your own CSV dataset you should find success in subclassing para_nmt.py. Specifically focusing on the setup function here: https://github.com/Clyde013/Paraphrase-OPT/blob/50f9f7021d006e752b1b58a863c6ba7785e4574f/training_datasets/para_nmt/para_nmt.py#L59

The loading of your csv file can be done similar to loading any other huggingface dataset.

```
from datasets import load_dataset
dataset = load_dataset("csv", data_files="my_file.csv")
```

Then, follow the documentation here to process the CSV dataset however you want: https://huggingface.co/docs/datasets/process

Good luck!
